# Generated by Django 3.2 on 2025-10-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_a', models.FloatField()),
                ('input_b', models.FloatField()),
                ('input_c', models.FloatField()),
                ('input_d', models.FloatField()),
                ('input_e', models.FloatField()),
                ('average', models.FloatField()),
                ('is_average_greater_50', models.BooleanField()),
                ('positive_count', models.IntegerField()),
                ('is_positive_count_even', models.BooleanField()),
                ('sorted_list_gt_10_str', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calculation_entries',
            },
        ),
    ]
